# Generated by Django 5.0.4 on 2024-06-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='canvas_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
