# Generated by Django 5.0.4 on 2024-05-10 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 10, 11, 29, 66755, tzinfo=datetime.timezone.utc)),
        ),
    ]
