# Generated by Django 5.0.4 on 2024-05-14 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workout_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 5, 26, 0, 31564, tzinfo=datetime.timezone.utc)),
        ),
    ]
