# Generated by Django 5.0.4 on 2024-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_workout_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
